remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Are Tech Stocks More Volatile than Healthcare Stocks?
description: |
  Personal Project about the Volatility of Tech and Healthcare Stocks 
  by Kenny Tran (kat009@ucsd.edu)
  July, 2023
